services:
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: practice-swagger-ui
    ports:
      - "8086:8080"
    environment:
      SWAGGER_JSON: /usr/share/nginx/html/docs/api-docs.json
    volumes:
      - ./docker/swagger/docs:/usr/share/nginx/html/docs:ro
    restart: unless-stopped
